version: "3"
services:
  stock:
    image: gocreating/lation:$IMAGE_TAG
    ports:
      # external port: internal port
      - "5555:8000"
    environment:
      - APP=stock
      - HOST=https://stock-api.lation.app:5555
      - FRONTEND_HOST=https://stock.lation.app
      - DB_URL=$STOCK_DB_URL
      - OAUTH_GOOGLE_CLIENT_ID=$STOCK_OAUTH_GOOGLE_CLIENT_ID
      - OAUTH_GOOGLE_CLIENT_SECRET=$STOCK_OAUTH_GOOGLE_CLIENT_SECRET
      - OAUTH_LINE_CLIENT_ID=$STOCK_OAUTH_LINE_CLIENT_ID
      - OAUTH_LINE_CLIENT_SECRET=$STOCK_OAUTH_LINE_CLIENT_SECRET
      - LINE_CHANNEL_ACCESS_TOKEN=$STOCK_LINE_CHANNEL_ACCESS_TOKEN
      - SMTP_USER=$SMTP_USER
      - SMTP_PASSWORD=$SMTP_PASSWORD
