version: "3"
services:
  web_server:
    image: gocreating/lation:$IMAGE_TAG
    ports:
      # external port: internal port
      - "5555:8000"
    environment:
      - APP=stock
      - HOST=https://stock-api.lation.app:5555
      - FRONTEND_HOST=https://stock.lation.app
      - DB_URL=$STOCK_DB_URL
      - OAUTH_GOOGLE_CLIENT_ID=691914720758-vovshlq9pujejchgfbkuiujdbc8f6ail.apps.googleusercontent.com
      - OAUTH_GOOGLE_CLIENT_SECRET=$STOCK_OAUTH_GOOGLE_CLIENT_SECRET
      - OAUTH_LINE_CLIENT_ID=1655591797
      - OAUTH_LINE_CLIENT_SECRET=$STOCK_OAUTH_LINE_CLIENT_SECRET
      - LINE_CHANNEL_ACCESS_TOKEN=$STOCK_LINE_CHANNEL_ACCESS_TOKEN
      - LINE_BOT_BASIC_ID=322mhruw
      - SMTP_USER=$SMTP_USER
      - SMTP_PASSWORD=$SMTP_PASSWORD
    volumes:
      - static-files:/app/lation/modules/stock/static
  job_scheduler:
    image: gocreating/lation:$IMAGE_TAG
    environment:
      - APP=stock
      - DB_URL=$STOCK_DB_URL
      - MESSAGE_QUEUE_URL=$MESSAGE_QUEUE_URL
    volumes:
      - static-files:/app/lation/modules/stock/static
    entrypoint: python
    command: lation.py job scheduler
  job_worker:
    image: gocreating/lation:$IMAGE_TAG
    environment:
      - APP=stock
      - DB_URL=$STOCK_DB_URL
      - MESSAGE_QUEUE_URL=$MESSAGE_QUEUE_URL
      - LINE_CHANNEL_ACCESS_TOKEN=$STOCK_LINE_CHANNEL_ACCESS_TOKEN
    volumes:
      - static-files:/app/lation/modules/stock/static
    entrypoint: python
    command: lation.py job worker

volumes:
  static-files:
