from lation.core.env import get_env


FTX_API_KEY_ROOT = get_env('FTX_API_KEY_ROOT')
FTX_API_SECRET_ROOT = get_env('FTX_API_SECRET_ROOT')

FTX_API_KEY_ME = get_env('FTX_API_KEY_ME')
FTX_API_SECRET_ME = get_env('FTX_API_SECRET_ME')

FTX_API_KEY_MOM = get_env('FTX_API_KEY_MOM')
FTX_API_SECRET_MOM = get_env('FTX_API_SECRET_MOM')

FTX_API_KEY_SISTER = get_env('FTX_API_KEY_SISTER')
FTX_API_SECRET_SISTER = get_env('FTX_API_SECRET_SISTER')
