version: "3"
services:
  web_server:
    build: ../../
    ports:
      # external port: internal port
      - "8000:8000"
    environment:
      - APP=coin
      - DB_URL=xxx
      - HOST=https://localhost:8000
      - FRONTEND_HOST=http://localhost:3000
      - OAUTH_LINE_CLIENT_ID=xxx
      - OAUTH_LINE_CLIENT_SECRET=xxx
