version: "3"
services:
  web_server:
    image: gocreating/lation:$IMAGE_TAG
    ports:
      # external port: internal port
      - "443:8000" # Must use port 443 as required by ecpay
    environment:
      - APP=coin
      - DB_URL=$COIN_DB_URL
      - HOST=https://coin-api.lation.app
      - FRONTEND_HOST=https://coin.lation.app
      - OAUTH_LINE_CLIENT_ID=1655706895
      - OAUTH_LINE_CLIENT_SECRET=$COIN_OAUTH_LINE_CLIENT_SECRET
      - PAYMENT_GATEWAY_ECPAY_MERCHANT_ID=$COIN_PAYMENT_GATEWAY_ECPAY_MERCHANT_ID
      - PAYMENT_GATEWAY_ECPAY_HASH_KEY=$COIN_PAYMENT_GATEWAY_ECPAY_HASH_KEY
      - PAYMENT_GATEWAY_ECPAY_HASH_IV=$COIN_PAYMENT_GATEWAY_ECPAY_HASH_IV
  job_scheduler:
    image: gocreating/lation:$IMAGE_TAG
    environment:
      - APP=coin
      - DB_URL=$COIN_DB_URL
      - MESSAGE_QUEUE_URL=$MESSAGE_QUEUE_URL
    entrypoint: python
    command: lation.py job scheduler
  job_worker:
    image: gocreating/lation:$IMAGE_TAG
    environment:
      - APP=coin
      - DB_URL=$COIN_DB_URL
      - MESSAGE_QUEUE_URL=$MESSAGE_QUEUE_URL
      - PAYMENT_GATEWAY_ECPAY_MERCHANT_ID=$COIN_PAYMENT_GATEWAY_ECPAY_MERCHANT_ID
      - PAYMENT_GATEWAY_ECPAY_HASH_KEY=$COIN_PAYMENT_GATEWAY_ECPAY_HASH_KEY
      - PAYMENT_GATEWAY_ECPAY_HASH_IV=$COIN_PAYMENT_GATEWAY_ECPAY_HASH_IV
    entrypoint: python
    command: lation.py job worker
