version: '3.1'

services:
  db:
    image: mysql/mysql-server:8.0.21
    restart: always
    environment:
      MYSQL_USER: lation-combo-user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
    ports:
      - 3306:3306
